"""Add LearningCandidate models for Phase 18.4

Revision ID: bc766b504cde
Revises: f260d77c991d
Create Date: 2026-08-19 04:17:40.200200

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bc766b504cde'
down_revision: Union[str, Sequence[str], None] = 'f260d77c991d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('learning_candidates',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('candidate_type', sa.Enum('THRESHOLD_ADJUSTMENT', 'DETECTOR_REVIEW', 'TECHNIQUE_REVIEW', 'CLASSIFIER_REVIEW', name='candidatetype'), nullable=False),
    sa.Column('target', sa.String(), nullable=False),
    sa.Column('technique', sa.String(), nullable=True),
    sa.Column('detector', sa.String(), nullable=True),
    sa.Column('current_value', sa.Float(), nullable=True),
    sa.Column('proposed_value', sa.Float(), nullable=True),
    sa.Column('sample_size', sa.Integer(), nullable=False),
    sa.Column('false_positive_count', sa.Integer(), nullable=False),
    sa.Column('false_negative_count', sa.Integer(), nullable=False),
    sa.Column('confidence', sa.Enum('LOW', 'MEDIUM', 'HIGH', 'INSUFFICIENT', name='candidateconfidence'), nullable=False),
    sa.Column('reason', sa.String(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'APPROVED', 'REJECTED', 'APPLIED', name='candidatestatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('reviewed_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['reviewed_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_learning_candidates_status'), 'learning_candidates', ['status'], unique=False)
    op.create_index(op.f('ix_learning_candidates_target'), 'learning_candidates', ['target'], unique=False)
    op.create_table('candidate_evidence',
    sa.Column('candidate_id', sa.UUID(), nullable=False),
    sa.Column('feedback_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['candidate_id'], ['learning_candidates.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['feedback_id'], ['feedback.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('candidate_id', 'feedback_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('candidate_evidence')
    op.drop_index(op.f('ix_learning_candidates_target'), table_name='learning_candidates')
    op.drop_index(op.f('ix_learning_candidates_status'), table_name='learning_candidates')
    op.drop_table('learning_candidates')
    # ### end Alembic commands ###
