"""Add feedback table

Revision ID: f260d77c991d
Revises: 15c6fe88fe0e
Create Date: 2026-08-18 19:51:52.153327

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f260d77c991d'
down_revision: Union[str, Sequence[str], None] = '15c6fe88fe0e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('feedback',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('scan_id', sa.UUID(), nullable=False),
    sa.Column('detection_id', sa.UUID(), nullable=False),
    sa.Column('analyst_id', sa.UUID(), nullable=False),
    sa.Column('label', sa.Enum('CORRECT', 'FALSE_POSITIVE', name='feedbacklabel'), nullable=False),
    sa.Column('technique', sa.String(), nullable=True),
    sa.Column('risk_score', sa.Integer(), nullable=False),
    sa.Column('severity', sa.String(), nullable=False),
    sa.Column('transformations', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('obfuscation_detected', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['analyst_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['detection_id'], ['detections.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['scan_id'], ['scans.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('detection_id', 'analyst_id', name='uq_feedback_detection_analyst')
    )
    op.create_index(op.f('ix_feedback_analyst_id'), 'feedback', ['analyst_id'], unique=False)
    op.create_index(op.f('ix_feedback_created_at'), 'feedback', ['created_at'], unique=False)
    op.create_index(op.f('ix_feedback_detection_id'), 'feedback', ['detection_id'], unique=False)
    op.create_index(op.f('ix_feedback_scan_id'), 'feedback', ['scan_id'], unique=False)
    op.create_index(op.f('ix_feedback_technique'), 'feedback', ['technique'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_feedback_technique'), table_name='feedback')
    op.drop_index(op.f('ix_feedback_scan_id'), table_name='feedback')
    op.drop_index(op.f('ix_feedback_detection_id'), table_name='feedback')
    op.drop_index(op.f('ix_feedback_created_at'), table_name='feedback')
    op.drop_index(op.f('ix_feedback_analyst_id'), table_name='feedback')
    op.drop_table('feedback')
    sa.Enum(name='feedbacklabel').drop(op.get_bind())
    # ### end Alembic commands ###
