"""Phase 18.6 learning application

Revision ID: fbd0932d8f63
Revises: 680f20d8a839
Create Date: 2026-08-20 03:56:36.538583

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fbd0932d8f63'
down_revision: Union[str, Sequence[str], None] = '680f20d8a839'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('learning_configs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_learning_configs_active'), 'learning_configs', ['active'], unique=False)
    op.create_index(op.f('ix_learning_configs_version'), 'learning_configs', ['version'], unique=True)
    op.create_table('learning_applications',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('candidate_id', sa.UUID(), nullable=False),
    sa.Column('config_id', sa.UUID(), nullable=False),
    sa.Column('applied_by', sa.UUID(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('change_type', sa.String(), nullable=False),
    sa.Column('target', sa.String(), nullable=False),
    sa.Column('previous_value', sa.Float(), nullable=True),
    sa.Column('new_value', sa.Float(), nullable=False),
    sa.Column('status', sa.Enum('APPLIED', 'ROLLED_BACK', name='applicationstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('activated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('rolled_back_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('rollback_reason', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['applied_by'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['candidate_id'], ['learning_candidates.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['config_id'], ['learning_configs.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('candidate_id')
    )
    op.create_index(op.f('ix_learning_applications_status'), 'learning_applications', ['status'], unique=False)
    op.create_table('learning_rules',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('config_id', sa.UUID(), nullable=False),
    sa.Column('candidate_id', sa.UUID(), nullable=False),
    sa.Column('rule_type', sa.String(), nullable=False),
    sa.Column('target', sa.String(), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['candidate_id'], ['learning_candidates.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['config_id'], ['learning_configs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_learning_rules_config_id'), 'learning_rules', ['config_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_learning_rules_config_id'), table_name='learning_rules')
    op.drop_table('learning_rules')
    op.drop_index(op.f('ix_learning_applications_status'), table_name='learning_applications')
    op.drop_table('learning_applications')
    op.drop_index(op.f('ix_learning_configs_version'), table_name='learning_configs')
    op.drop_index(op.f('ix_learning_configs_active'), table_name='learning_configs')
    op.drop_table('learning_configs')
    # ### end Alembic commands ###
